"""Render governance artifacts from their sources of truth.

Two generators, one principle — *governance metadata is derived, never
hand-maintained*:

* **PII tag DDL** is generated from the data contracts' ``pii`` flags
  (``quality/contracts``). If a contract marks a field as PII, the SQL that
  tags it in Unity Catalog exists automatically; nobody keeps a second list.
* **The access matrix** is rendered from ``grants.yaml`` into reviewer-
  friendly markdown — the artifact an auditor actually reads.

Outputs land in ``governance/unity_catalog/generated/`` and are committed:
CI regenerates and fails on diff, which is what keeps the derived artifacts
honest (the same trick as generated API docs).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

from quality.contracts.loader import load_contracts

GENERATED_DIR = Path(__file__).resolve().parent / "generated"
GRANTS_PATH = Path(__file__).resolve().parent / "grants.yaml"

# silver holds the contract-shaped tables; bronze holds raw payloads whose
# columns aren't individually taggable (the whole payload is treated as
# restricted — see the compliance matrix).
TAGGED_CATALOG_SCHEMA = "silver.banking"


def render_pii_tag_sql() -> str:
    """Unity Catalog ``SET TAGS`` statements derived from contract PII flags."""
    lines = [
        "-- GENERATED by governance/unity_catalog/render.py — do not edit.",
        "-- Source of truth: quality/contracts/definitions/*.yaml (pii flags).",
        "-- Apply with a UC-enabled SQL warehouse or spark.sql loop.",
        "",
    ]
    for name, contract in sorted(load_contracts().items()):
        lines.append(f"-- {name} (contract v{contract.version})")
        for field in contract.fields:
            if not field.pii:
                continue
            lines.append(
                f"ALTER TABLE {TAGGED_CATALOG_SCHEMA}.{name} "
                f"ALTER COLUMN {field.name} "
                f"SET TAGS ('pii' = 'true', 'pii_category' = '{field.pii_category}');"
            )
        lines.append("")
    return "\n".join(lines)


def render_access_matrix() -> str:
    """Markdown access matrix from grants.yaml, for review and audit evidence."""
    raw: dict[str, Any] = yaml.safe_load(GRANTS_PATH.read_text(encoding="utf-8"))
    principals = {p["name"]: p for p in raw["principals"]}
    securables = sorted({g["securable"] for g in raw["grants"]})

    lines = [
        "<!-- GENERATED by governance/unity_catalog/render.py - do not edit. -->",
        "<!-- Source of truth: governance/unity_catalog/grants.yaml -->",
        "",
        "# Unity Catalog Access Matrix",
        "",
        "| Principal | Kind | " + " | ".join(s.split("/", 1)[1] for s in securables) + " |",
        "|---|---|" + "---|" * len(securables),
    ]
    for name, principal in sorted(principals.items()):
        cells = []
        for securable in securables:
            privileges = [
                g["privileges"]
                for g in raw["grants"]
                if g["principal"] == name and g["securable"] == securable
            ]
            if privileges:
                short = ", ".join(
                    p.replace("USE_CATALOG", "USE").replace("USE_SCHEMA", "")
                    for p in privileges[0]
                    if p not in ("USE_CATALOG", "USE_SCHEMA")
                )
                cells.append(short or "USE")
            else:
                cells.append("—")
        lines.append(f"| {name} | {principal['kind']} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "PII inventory (derived from contracts):",
        "",
        "| Table | Column | Category |",
        "|---|---|---|",
    ]
    for name, contract in sorted(load_contracts().items()):
        for field in contract.pii_fields:
            lines.append(f"| {name} | {field.name} | {field.pii_category} |")
    lines.append("")
    return "\n".join(lines)


def write_generated() -> list[Path]:
    GENERATED_DIR.mkdir(exist_ok=True)
    outputs = {
        GENERATED_DIR / "pii_tags.sql": render_pii_tag_sql(),
        GENERATED_DIR / "access_matrix.md": render_access_matrix(),
    }
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    return list(outputs)


def main() -> int:
    for path in write_generated():
        print(f"rendered {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
