"""Synthetic banking governance corpus.

Generates the internal documents a real bank's data platform would be asked
about — retention policy, AML monitoring standard, incident runbook, DQ
standard, access policy, PII handling — as markdown with stable headings.
Document *content* is fixed (the RAG demo asserts answers against it);
Faker fills in the incidental metadata (owners, doc ids, review dates) so
regenerated corpora look alive without breaking determinism under a seed.

No real bank documents were used; everything here is written for this repo.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from pathlib import Path

from faker import Faker


@dataclass(frozen=True)
class GeneratedDoc:
    slug: str
    title: str
    path: Path


def _front_matter(faker: Faker, rng: random.Random, title: str, slug: str) -> str:
    doc_id = f"POL-{rng.randint(100, 999)}"
    return (
        f"# {title}\n\n"
        f"Document ID: {doc_id} | Owner: {faker.name()}, Data Governance Office | "
        f"Classification: Internal | Last review: 2025-{rng.randint(10, 12):02d}-"
        f"{rng.randint(1, 28):02d}\n"
    )


def _doc_retention(faker: Faker, rng: random.Random) -> tuple[str, str, str]:
    title = "Data Retention and Archival Policy"
    body = """
## Purpose

Defines how long each class of data is retained across the lakehouse layers
and when it must be archived or destroyed.

## Retention periods by data class

The following minimum retention periods apply from the date a record is
created or last modified:

- Transaction records (posted account transactions): retained for 10 years,
  in line with FISC-style guidance for transaction evidence in banking
  systems.
- Customer master data: retained for the duration of the relationship plus
  7 years after account closure.
- Loan application records: retained for 7 years after final decision,
  including rejected applications unless erasure is requested.
- Pipeline operational metadata (run metrics, quality results): retained
  for 2 years for capacity planning and audit of processing behavior.
- Quarantined records: retained for 90 days pending investigation, then
  purged unless attached to an open incident.

## Archival

Delta time travel history on silver tables is vacuumed to 30 days; long-term
history is preserved by the SCD Type 2 design itself, which never physically
deletes closed versions inside the retention window.

## Erasure requests

Data-minimization deletions (for example, a rejected loan applicant
requesting erasure) are implemented as CDC delete events: the current
version is closed, direct identifiers become eligible for masking, and the
audit skeleton (keys, timestamps) is preserved as permitted.
"""
    return title, "data-retention-policy", body


def _doc_aml(faker: Faker, rng: random.Random) -> tuple[str, str, str]:
    title = "AML Transaction Monitoring Standard"
    body = """
## Scope

Applies to all posted transactions flowing through the gold aggregation
layer. Screening outcomes are materialized as flags on
`gold.account_daily_metrics` for downstream case management.

## Screening rules

- Large transaction: any single transaction at or above the reporting
  threshold of 700,000 JPY-equivalent raises `large_txn_flag`.
- High velocity: six or more transactions on one account in a single day
  raises `high_velocity_flag`.
- Structuring (smurfing): three or more transactions in one day each
  falling between 85% and 100% of the reporting threshold raises
  `structuring_flag`. Repeated just-below-threshold activity is the
  primary structuring indicator.

## Case handling

Flagged account-days are reviewed within one business day. False-positive
rates are tracked per rule and thresholds are recalibrated quarterly.
Escalations follow the Incident Response Runbook.
"""
    return title, "aml-monitoring-standard", body


def _doc_runbook(faker: Faker, rng: random.Random) -> tuple[str, str, str]:
    title = "Pipeline Incident Response Runbook"
    body = """
## Severity classification

- SEV-1: data loss, corruption reaching gold, or a regulatory reporting
  deadline at risk. Page the on-call engineer immediately.
- SEV-2: pipeline failure with stale downstream data but no corruption;
  respond within 4 business hours.
- SEV-3: quality degradation (quarantine spike, DQ warnings) with no
  consumer impact yet; triage within one business day.

## First response steps

1. Read the incident report generated by the observability agent; it names
   the failing step, affected tables, and probable cause.
2. Check the quarantine tables before touching checkpoints: a quarantine
   spike usually means an upstream payload change, not a pipeline bug.
3. Never delete a streaming checkpoint as a first measure. Checkpoint
   removal reprocesses the landing zone and can duplicate bronze appends.

## Quarantine investigation

Quarantined rows carry the raw payload and a violation reason. If the cause
is a contract change, follow the contract evolution process (new version,
compatibility check) rather than patching data in place.

## Postmortem

SEV-1 and SEV-2 incidents require a written postmortem within 5 business
days, including the metrics-table evidence and the remediation commit.
"""
    return title, "incident-response-runbook", body


def _doc_dq(faker: Faker, rng: random.Random) -> tuple[str, str, str]:
    title = "Data Quality Management Standard"
    body = """
## Quality gates by layer

- Bronze: structural validation only — parseability and envelope
  completeness. Broken events are quarantined with reasons, never dropped.
- Silver: contract enforcement — schema, nullability, enumerated domains.
  Violations quarantine with named rules.
- Gold and marts: business assertions via the DQ suites and dbt tests.

## Severity policy

Checks carry `error` or `warn` severity. Errors block promotion of the
affected table; warnings are recorded, surfaced in the observability
dashboard, and reviewed by the owning team within one business day.
Referential integrity checks default to `warn` because orphans typically
trace to quarantined upstream events rather than defects in the checked
table.

## Metrics

Every suite execution writes pass rates to the pipeline metrics table.
A pass rate below 95% on any silver table triggers a quality review.
"""
    return title, "data-quality-standard", body


def _doc_access(faker: Faker, rng: random.Random) -> tuple[str, str, str]:
    title = "Data Access Control Policy"
    body = """
## Principle

Least privilege by lakehouse layer, enforced as code (Terraform +
grants-as-code YAML) and reviewed on every change via pull request.

## Access tiers

- Analysts: SELECT on the gold catalog only. No access to bronze or silver
  under any circumstances; raw payloads and unmasked PII live there.
- Data engineers: full modify rights on bronze and silver, read on gold.
- Pipeline service principals: scoped to exactly the layers their stage
  writes; the ingestion principal cannot read silver.

## PII handling

Columns are tagged from the data-contract PII classification. Direct
identifiers never propagate past silver; analyst-facing marts are
PII-minimized by construction rather than masked after the fact.

## Review

Access grants are recertified quarterly. The generated access matrix in the
governance directory is the audit evidence of record.
"""
    return title, "access-control-policy", body


def _doc_pii(faker: Faker, rng: random.Random) -> tuple[str, str, str]:
    title = "PII Handling Standard"
    body = """
## Classification categories

- direct_identifier: name, email, phone, address — identifies a person
  outright.
- quasi_identifier: attributes that identify in combination (address
  fragments, counterparty names).
- sensitive: credit scores and similar evaluative data.
- financial: balances and transaction amounts at personal grain.

## Handling rules by category

Direct identifiers are confined to the silver layer and masked or excluded
in all analyst-facing marts. Sensitive fields require a documented business
justification for any new consumer. Financial-grain data may appear in
marts only aggregated or normalized, never as raw personal amounts joined
to direct identifiers.

## Source of truth

The data contracts carry the `pii` classification per field; Unity Catalog
column tags and the audit inventory are generated from them. Adding a PII
field without classification fails contract validation.
"""
    return title, "pii-handling-standard", body


GENERATORS = [_doc_retention, _doc_aml, _doc_runbook, _doc_dq, _doc_access, _doc_pii]


def generate_corpus(out_dir: Path, seed: int = 42) -> list[GeneratedDoc]:
    """Write the corpus to ``out_dir``; deterministic for a given seed."""
    rng = random.Random(seed)
    faker = Faker()
    faker.seed_instance(seed)
    out_dir.mkdir(parents=True, exist_ok=True)
    docs: list[GeneratedDoc] = []
    for generator in GENERATORS:
        title, slug, body = generator(faker, rng)
        path = out_dir / f"{slug}.md"
        path.write_text(_front_matter(faker, rng, title, slug) + body, encoding="utf-8")
        docs.append(GeneratedDoc(slug=slug, title=title, path=path))
    return docs
